-- MySQL Script generated by MySQL Workbench
-- Mon Oct  4 09:47:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema StarWarsWikiDatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema StarWarsWikiDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `StarWarsWikiDB` DEFAULT CHARACTER SET utf8 ;
USE `StarWarsWikiDB` ;

-- -----------------------------------------------------
-- Table `StarWarsWikiDatabase`.`AccountInformation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StarWarsWikiDB`.`AccountInformation` (
  `AccountKey` INT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Initials` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `FullName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Character` VARCHAR(45) NULL,
  `Movie` VARCHAR(45) NULL,
  `Serie` VARCHAR(45) NULL,
  `Fight` VARCHAR(100) NULL,
  `Jedi` VARCHAR(45) NULL,
  PRIMARY KEY (`AccountKey`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StarWarsWikiDatabase`.`Reactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StarWarsWikiDB`.`Reactions` (
  `ReactionKey` INT NOT NULL,
  `Text` LONGTEXT NOT NULL,
  `Date` DATE NOT NULL,
  `Theme` VARCHAR(150) NOT NULL,
  `AccountInformation_AccountKey` INT NOT NULL,
  PRIMARY KEY (`ReactionKey`),
  INDEX `fk_Reactions_AccountInformation_idx` (`AccountInformation_AccountKey` ASC),
  CONSTRAINT `fk_Reactions_AccountInformation`
    FOREIGN KEY (`AccountInformation_AccountKey`)
    REFERENCES `StarWarsWikiDatabase`.`AccountInformation` (`AccountKey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
